#!/usr/bin/env python3
import sys
import json
import os
from pathlib import Path

def main():
    if len(sys.argv) < 5:
        print("Usage: python dolphin_postprocess.py <raw_json> <image_path> <output_dir> <mode>")
        sys.exit(1)

    raw_json_path = sys.argv[1]
    image_path = sys.argv[2]
    output_dir = Path(sys.argv[3])
    mode = sys.argv[4]

    if not os.path.exists(raw_json_path):
        print(f"Error: JSON file not found at {raw_json_path}")
        sys.exit(1)

    try:
        with open(raw_json_path, 'r') as f:
            data = json.load(f)
    except json.JSONDecodeError:
        print("Error: Invalid JSON response.")
        sys.exit(1)

    # Extract Content
    # The server returns 'raw_text_output'
    raw_text = data.get("raw_text_output", "")
    metadata = data.get("metadata", {})

    if not raw_text:
        print("Warning: No text output found in response.")
        raw_text = "(No output generated)"

    # Format Output based on Mode
    output_filename = f"analysis_{mode}.md"
    output_path = output_dir / output_filename

    markdown_content = f"""# Dolphin-Perception Analysis
**Mode:** {mode}
**Source:** {os.path.basename(image_path)}
**Timestamp:** {metadata.get('timestamp', 'N/A')}

## Result
{raw_text}

---
*Generated by Dolphin-v2 Local Hub*
"""
    
    # Save Markdown
    with open(output_path, 'w') as f:
        f.write(markdown_content)

    print(f"✅ Analysis saved to: {output_path}")

    # Optional: If table mode, try to extract CSV? 
    # For now, Markdown is sufficient as the model outputs Markdown tables.

if __name__ == "__main__":
    main()
